vich_uploader:
    db_driver: orm

    mappings:
        upload_picture:
            uri_prefix: /images/uploads
            upload_destination: '%upload_directory%'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
